spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:9999/healthcare?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: admin
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  config:
    location: project.healthcare.config

server:
  port: 8080
