spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:port/databse?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: username
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    location: project.healthcare.config

server:
  port: 8080
